imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale: %locale%
    session:
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        unix_socket: %database_unix_socket%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false
            


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

services:
   dunglas.carrental.admin.renting:
      class: Dunglas\Bundle\CarRentalBundle\Admin\RentingAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: "Car Rental", label: Renting }
      arguments: [null, Dunglas\Bundle\CarRentalBundle\Entity\Renting, null]
   
   dunglas.carrental.admin.payment:
      class: Dunglas\Bundle\CarRentalBundle\Admin\PaymentAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: "Car Rental", label: Payment }
      arguments: [null, Dunglas\Bundle\CarRentalBundle\Entity\Payment, null]
  
   dunglas.carrental.admin.customer:
      class: Dunglas\Bundle\CarRentalBundle\Admin\CustomerAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: "Car Rental", label: Customer }
      arguments: [null, Dunglas\Bundle\CarRentalBundle\Entity\Customer, null]
  
   dunglas.carrental.admin.vehicle:
      class: Dunglas\Bundle\CarRentalBundle\Admin\VehicleAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Vehicle, label: Vehicle }
      arguments: [null, Dunglas\Bundle\CarRentalBundle\Entity\Vehicle, null]
   
   dunglas.carrental.admin.manufacturer:
      class: Dunglas\Bundle\CarRentalBundle\Admin\ManufacturerAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Config, label: Manufacturer }
      arguments: [null, Dunglas\Bundle\CarRentalBundle\Entity\Manufacturer, null]
   
   dunglas.carrental.admin.model:
      class: Dunglas\Bundle\CarRentalBundle\Admin\ModelAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Config, label: Model }
      arguments: [null, Dunglas\Bundle\CarRentalBundle\Entity\Model, null]
   
   dunglas.carrental.admin.fuel:
      class: Dunglas\Bundle\CarRentalBundle\Admin\FuelAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Config, label: Fuel }
      arguments: [null, Dunglas\Bundle\CarRentalBundle\Entity\Fuel, null]
