# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

homepage:
    pattern:  /
    defaults: { _controller: DunglasCarRentalBundle:Customer:index }

car_rental:
    resource: "@DunglasCarRentalBundle/Resources/config/routing.yml"